#!/usr/bin/env python3
"""Generate a LaTeX summary report from top-50.sqlite."""

import sqlite3
from collections import Counter
from pathlib import Path

DB_PATH = Path(__file__).parent / "top-50.sqlite"
OUT_PATH = Path(__file__).parent / "summary.tex"


def q(conn, sql, params=()):
    return conn.execute(sql, params).fetchall()


def latex_escape(s):
    if s is None:
        return r"\textit{N/A}"
    return (
        str(s)
        .replace("_", r"\_")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("#", r"\#")
        .replace("https://", "")
        .replace("http://", "")
    )


def fmt(val, decimals=1):
    if val is None:
        return "---"
    if isinstance(val, float):
        return f"{val:.{decimals}f}"
    return str(val)


def top(rows, n=1):
    """Return the label of the nth most common row (rows sorted DESC by count)."""
    return latex_escape(rows[n - 1][0]) if len(rows) >= n else "---"


def build_report(conn):
    lines = []

    def emit(*args):
        lines.append(" ".join(str(a) for a in args))

    # ------------------------------------------------------------------ #
    # Document header
    # ------------------------------------------------------------------ #
    # emit(r"\documentclass[a4paper,10pt,twocolumn]{article}")
    # emit(r"\usepackage[margin=2cm,columnsep=0.6cm]{geometry}")
    # emit(r"\usepackage{booktabs}")
    # emit(r"\usepackage{array}")
    # emit(r"\usepackage{xcolor}")
    # emit(r"\usepackage{hyperref}")
    # emit(r"\usepackage{caption}")
    # emit(r"\usepackage{parskip}")
    # emit(r"\usepackage{multirow}")
    # emit(r"\usepackage{makecell}")
    # emit(r"\usepackage{amssymb}")
    # emit(r"\hypersetup{colorlinks=true,linkcolor=blue,urlcolor=blue}")
    # emit(r"\setlength{\tabcolsep}{4pt}")
    # emit(r"\title{\textbf{Cookie Notice Audit: Top-50 Websites}\\[0.4em]")
    # emit(r"  \large Automated Analysis Report}")
    # emit(r"\date{\today}")
    # emit(r"\author{Generated by \texttt{generate\_summary.py}}")
    # emit(r"\begin{document}")
    # emit(r"\maketitle")
    # emit(r"\tableofcontents")
    # emit(r"\newpage")

    # ------------------------------------------------------------------ #
    # 1. Overview
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Overview}")

    total_chrome    = q(conn, "SELECT COUNT(*) FROM chrome_scans")[0][0]
    total_brave     = q(conn, "SELECT COUNT(*) FROM brave_scans")[0][0]
    error_count     = q(conn, "SELECT COUNT(*) FROM chrome_scans WHERE is_error_page=1")[0][0]
    reachable       = total_chrome - error_count
    cookie_detected = q(conn, "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=1")[0][0]
    cookie_accepted = q(conn, "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_accepted=1")[0][0]

    emit(
        rf"An automated audit was performed on the top-{total_chrome} websites by Tranco rank. "
        rf"Of these, \textbf{{{error_count}}} ({error_count/total_chrome*100:.0f}\,\%) "
        r"could not be loaded successfully and were excluded from further analysis, "
        rf"leaving \textbf{{{reachable}}} reachable sites. "
        r"Each reachable site was visited with two browsers: "
        r"\textbf{Chrome} (to detect and classify cookie notices and capture accessibility metrics) "
        r"and \textbf{Brave} (to measure tracker and ad blocking)."
    )
    emit()
    emit(
        rf"A cookie notice was detected on \textbf{{{cookie_detected}}} of the {reachable} reachable sites "
        rf"({cookie_detected/reachable*100:.0f}\,\%), and was successfully accepted on "
        rf"\textbf{{{cookie_accepted}}} of those ({cookie_accepted/cookie_detected*100:.0f}\,\%)."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{High-level scan counts}")
    emit(r"\begin{tabular}{lr}")
    emit(r"\toprule Metric & Count \\ \midrule")
    emit(rf"Chrome scans & {total_chrome} \\")
    emit(rf"Brave scans  & {total_brave} \\")
    emit(rf"Unavailable (error) & {error_count} ({error_count/total_chrome*100:.0f}\,\%) \\")
    emit(rf"Reachable sites & {reachable} \\")
    emit(rf"Cookie notice detected & {cookie_detected} ({cookie_detected/reachable*100:.0f}\,\%) \\")
    emit(rf"Cookie notice accepted & {cookie_accepted} ({cookie_accepted/cookie_detected*100:.0f}\,\%) \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    # ------------------------------------------------------------------ #
    # 2. Unavailable / Error Sites
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Unavailable Sites}")

    def error_category(page_error, http_status):
        if page_error and "ERR_NAME_NOT_RESOLVED" in page_error:
            return "DNS not resolved"
        if page_error and "ERR_CONNECTION_REFUSED" in page_error:
            return "Connection refused"
        if page_error and "ERR_CERT" in page_error:
            return "TLS/certificate error"
        if page_error and "ERR_ABORTED" in page_error:
            return "Request aborted"
        if http_status == 404:
            return "HTTP 404 Not Found"
        if http_status == 403:
            return "HTTP 403 Forbidden"
        if http_status is not None and http_status >= 400:
            return f"HTTP {http_status}"
        return "Other error"

    error_rows = q(
        conn,
        "SELECT url, http_status, page_error FROM chrome_scans WHERE is_error_page=1 ORDER BY url",
    )
    cat_counts = Counter(error_category(pe, hs) for _, hs, pe in error_rows)
    top_error_cat = cat_counts.most_common(1)[0]
    dns_count = cat_counts.get("DNS not resolved", 0)
    http4xx_count = sum(v for k, v in cat_counts.items() if k.startswith("HTTP"))

    emit(
        rf"Of the {total_chrome} sites scanned, \textbf{{{error_count}}} failed to load. "
        rf"The most common failure was \textbf{{{latex_escape(top_error_cat[0])}}} "
        rf"({top_error_cat[1]} sites), which typically indicates infrastructure or CDN domains "
        r"(e.g.\ \texttt{akamai.net}, \texttt{akadns.net}) that do not serve end-user web pages. "
        rf"A further {http4xx_count} site(s) returned HTTP 4xx error codes. "
        r"All unavailable sites were excluded from cookie-notice and accessibility analysis."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Error categories for unavailable sites}")
    emit(r"\begin{tabular}{lr}")
    emit(r"\toprule Error type & Count \\ \midrule")
    for cat, cnt in cat_counts.most_common():
        emit(rf"  {latex_escape(cat)} & {cnt} \\")
    emit(r"\midrule")
    emit(rf"  \textbf{{Total}} & \textbf{{{error_count}}} \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    emit(
        r"Table~\ref{tab:errors} lists every unavailable site. "
        r"Sites returning HTTP 404 are predominantly Google-owned infrastructure "
        r"domains (\texttt{googleapis.com}, \texttt{gstatic.com}, etc.)\ that redirect "
        r"rather than serving a browsable page."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Per-site error details}\label{tab:errors}")
    emit(r"\begin{tabular}{>{\ttfamily}p{3cm} r p{3cm}}")
    emit(r"\toprule \normalfont URL & HTTP & Category \\ \midrule")
    for url, hs, pe in error_rows:
        cat = error_category(pe, hs)
        status_str = str(hs) if hs else "---"
        emit(rf"  {latex_escape(url)} & {status_str} & {latex_escape(cat)} \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    # ------------------------------------------------------------------ #
    # 3. Cookie Notice Classification
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Cookie Notice Classification}")

    emit(r"\subsubsection{Position}")

    pos_rows = q(
        conn,
        "SELECT COALESCE(cookie_position,'unknown'), COUNT(*) "
        "FROM chrome_scans WHERE cookie_notice_detected=1 "
        "GROUP BY cookie_position ORDER BY COUNT(*) DESC",
    )
    top_pos, top_pos_cnt = pos_rows[0]
    second_pos, second_pos_cnt = pos_rows[1] if len(pos_rows) > 1 else ("", 0)

    emit(
        rf"Cookie notices appeared most commonly as a \textbf{{{latex_escape(top_pos)}}} "
        rf"({top_pos_cnt} of {cookie_detected} sites, "
        rf"{top_pos_cnt/cookie_detected*100:.0f}\,\%), "
        rf"followed by \texttt{{{latex_escape(second_pos)}}} ({second_pos_cnt} sites). "
        r"One site used a full-page (\texttt{overall}) overlay that blocked all content "
        r"until the notice was addressed."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Cookie notice position}\label{tab:position}")
    emit(r"\begin{tabular}{lrr}")
    emit(r"\toprule Position & $n$ & \% \\ \midrule")
    for pos, cnt in pos_rows:
        emit(rf"  \texttt{{{latex_escape(pos)}}} & {cnt} & {cnt/cookie_detected*100:.0f}\,\% \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    emit(r"\subsubsection{Control Type (Response Options)}")

    ctrl_rows = q(
        conn,
        "SELECT COALESCE(cookie_control_type,'unknown'), COUNT(*) "
        "FROM chrome_scans WHERE cookie_notice_detected=1 "
        "GROUP BY cookie_control_type ORDER BY COUNT(*) DESC",
    )
    info_only = next((cnt for ct, cnt in ctrl_rows if ct == "informational_only"), 0)
    full_choice = next((cnt for ct, cnt in ctrl_rows if ct == "accept_reject_or_settings"), 0)

    emit(
        rf"The most common control type was \textbf{{informational only}} ({info_only} sites, "
        rf"{info_only/cookie_detected*100:.0f}\,\%), meaning visitors were shown a notice "
        r"but offered no meaningful opt-out. "
        rf"Only {full_choice} sites ({full_choice/cookie_detected*100:.0f}\,\%) provided "
        r"the full set of options: accept, reject, \emph{and} granular settings."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Cookie notice control type}\label{tab:control}")
    emit(r"\begin{tabular}{lrr}")
    emit(r"\toprule Control type & $n$ & \% \\ \midrule")
    for ctrl, cnt in ctrl_rows:
        emit(rf"  \texttt{{{latex_escape(ctrl)}}} & {cnt} & {cnt/cookie_detected*100:.0f}\,\% \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    emit(r"\subsubsection{Emphasized Option}")

    emph_rows = q(
        conn,
        "SELECT COALESCE(cookie_emphasized_option,'unknown'), COUNT(*) "
        "FROM chrome_scans WHERE cookie_notice_detected=1 "
        "GROUP BY cookie_emphasized_option ORDER BY COUNT(*) DESC",
    )
    equal_cnt = next((cnt for e, cnt in emph_rows if e == "equal"), 0)
    none_cnt  = next((cnt for e, cnt in emph_rows if e == "none"), 0)

    emit(
        rf"Of the {cookie_detected} detected notices, {none_cnt} had \texttt{{none}} as the "
        r"emphasized option, corresponding entirely to informational-only notices where no "
        r"choice is offered. "
        rf"Among notices that \emph{{do}} offer a choice, {equal_cnt} presented accept and "
        r"reject options with \textbf{equal} visual weight --- a positive finding indicating "
        r"no deliberate dark pattern was detected in these cases."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Emphasized option on cookie notices}\label{tab:emph}")
    emit(r"\begin{tabular}{lrr}")
    emit(r"\toprule Emphasized option & $n$ & \% \\ \midrule")
    for emph, cnt in emph_rows:
        emit(rf"  \texttt{{{latex_escape(emph)}}} & {cnt} & {cnt/cookie_detected*100:.0f}\,\% \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    emit(r"\subsubsection{Additional Features}")

    has_reject   = q(conn, "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=1 AND cookie_has_reject=1")[0][0]
    has_settings = q(conn, "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=1 AND cookie_has_settings=1")[0][0]
    pre_selected = q(conn, "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=1 AND cookie_pre_selected=1")[0][0]

    emit(
        rf"A reject button or link was present on {has_reject} of {cookie_detected} notices "
        rf"({has_reject/cookie_detected*100:.0f}\,\%), and a settings or preferences link on "
        rf"{has_settings} ({has_settings/cookie_detected*100:.0f}\,\%). "
        rf"No notices in this sample had options pre-selected, "
        r"meaning none defaulted consent to `on' before the user interacted."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Additional cookie notice features}")
    emit(r"\begin{tabular}{lrr}")
    emit(r"\toprule Feature & $n$ & \% \\ \midrule")
    emit(rf"Has reject button/link & {has_reject} & {has_reject/cookie_detected*100:.0f}\,\% \\")
    emit(rf"Has settings link & {has_settings} & {has_settings/cookie_detected*100:.0f}\,\% \\")
    emit(rf"Options pre-selected & {pre_selected} & {pre_selected/cookie_detected*100:.0f}\,\% \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    # ------------------------------------------------------------------ #
    # 4. Per-site cookie notice summary
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Per-Site Cookie Notice Summary}")

    emit(
        r"Table~\ref{tab:persite} lists every site where a cookie notice was detected "
        r"alongside its full classification. "
        r"The `Rej', `Set', and `Pre' columns indicate whether a reject button, "
        r"settings link, or pre-selected options were present (\checkmark) or absent (---), "
        r"respectively."
    )
    emit()

    site_rows = q(
        conn,
        """SELECT url, cookie_position, cookie_control_type, cookie_emphasized_option,
                  cookie_has_reject, cookie_has_settings, cookie_pre_selected
           FROM chrome_scans
           WHERE cookie_notice_detected=1
           ORDER BY url""",
    )

    emit(r"\begin{table*}[ht]\centering\footnotesize")
    emit(r"\caption{Per-site cookie notice classification}\label{tab:persite}")
    emit(r"\begin{tabular}{>{\ttfamily}p{2.3cm} p{1.5cm} p{2.5cm} p{1.1cm} c c c}")
    emit(r"\toprule \normalfont URL & Pos. & Control type & Emph. & Rej & Set & Pre \\ \midrule")
    for url, pos, ctrl, emph, rej, sett, pre in site_rows:
        def yn(v): return r"\checkmark" if v else "---"
        emit(
            rf"  {latex_escape(url)} & "
            rf"\scriptsize {latex_escape(pos)} & "
            rf"\scriptsize {latex_escape(ctrl)} & "
            rf"\scriptsize {latex_escape(emph)} & "
            rf"{yn(rej)} & {yn(sett)} & {yn(pre)} \\"
        )
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table*}")

    # ------------------------------------------------------------------ #
    # 5. Accessibility – Chrome (pre vs post accept)
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Accessibility Metrics (Chrome)}")

    avg = q(
        conn,
        """SELECT
             ROUND(AVG(pre_lh_score),1),  ROUND(AVG(post_lh_score),1),
             ROUND(AVG(pre_wave_error),1), ROUND(AVG(post_wave_error),1),
             ROUND(AVG(pre_wave_contrast),1), ROUND(AVG(post_wave_contrast),1),
             ROUND(AVG(pre_wave_alert),1), ROUND(AVG(post_wave_alert),1)
           FROM chrome_scans WHERE cookie_notice_detected=1""",
    )[0]

    lh_improved = q(
        conn,
        "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=1 "
        "AND post_lh_score > pre_lh_score",
    )[0][0]
    lh_declined = q(
        conn,
        "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=1 "
        "AND post_lh_score < pre_lh_score",
    )[0][0]
    lh_measured = q(
        conn,
        "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=1 "
        "AND pre_lh_score IS NOT NULL AND post_lh_score IS NOT NULL",
    )[0][0]

    emit(
        r"Lighthouse and WAVE accessibility tools were run both before and after accepting "
        r"the cookie notice, allowing a direct comparison of the notice's impact on "
        r"accessibility. "
        rf"Average Lighthouse scores were \textbf{{{fmt(avg[0])}}} pre-accept and "
        rf"\textbf{{{fmt(avg[1])}}} post-accept across the {cookie_detected} sites with "
        r"notices --- a negligible change, suggesting cookie notices themselves do not "
        r"substantially degrade page accessibility once removed. "
        rf"Of the {lh_measured} sites where both scores were available, "
        rf"{lh_improved} improved after acceptance and {lh_declined} declined."
    )
    emit()
    emit(
        rf"WAVE reported an average of \textbf{{{fmt(avg[2])}}} errors per page before "
        rf"acceptance and \textbf{{{fmt(avg[3])}}} after, with contrast errors averaging "
        rf"{fmt(avg[4])} and {fmt(avg[5])} respectively. "
        r"The small differences suggest that WAVE errors are largely attributable to "
        r"the underlying page rather than the cookie notice overlay."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Average accessibility metrics --- sites with cookie notices (Chrome)}")
    emit(r"\begin{tabular}{lrr}")
    emit(r"\toprule Metric & Pre & Post \\ \midrule")
    emit(rf"Lighthouse score & {fmt(avg[0])} & {fmt(avg[1])} \\")
    emit(rf"WAVE errors & {fmt(avg[2])} & {fmt(avg[3])} \\")
    emit(rf"WAVE contrast errors & {fmt(avg[4])} & {fmt(avg[5])} \\")
    emit(rf"WAVE alerts & {fmt(avg[6])} & {fmt(avg[7])} \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    lh_rows = q(
        conn,
        """SELECT url, pre_lh_score, post_lh_score,
                  pre_wave_error, post_wave_error,
                  pre_wave_contrast, post_wave_contrast
           FROM chrome_scans WHERE cookie_notice_detected=1
           ORDER BY url""",
    )

    # Notable outliers for prose
    worst_wave = max(lh_rows, key=lambda r: (r[3] or 0))
    worst_contrast = max(lh_rows, key=lambda r: (r[5] or 0))

    emit(
        rf"The site with the most WAVE errors pre-acceptance was "
        rf"\texttt{{{latex_escape(worst_wave[0])}}} ({fmt(worst_wave[3],0)} errors). "
        rf"The worst contrast errors were on \texttt{{{latex_escape(worst_contrast[0])}}} "
        rf"({fmt(worst_contrast[5],0)} contrast errors). "
        r"Per-site figures are in Table~\ref{tab:lh}."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Per-site Chrome accessibility (cookie-notice sites)}\label{tab:lh}")
    emit(r"\begin{tabular}{>{\ttfamily}p{2.2cm} r r r r r r}")
    emit(r"\toprule")
    emit(r"\normalfont URL & \multicolumn{2}{c}{LH} & \multicolumn{2}{c}{Err} & \multicolumn{2}{c}{Con} \\")
    emit(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}")
    emit(r"\normalfont & Pre & Post & Pre & Post & Pre & Post \\ \midrule")
    for url, pre_lh, post_lh, pre_we, post_we, pre_wc, post_wc in lh_rows:
        emit(
            rf"  {latex_escape(url)} & "
            rf"{fmt(pre_lh)} & {fmt(post_lh)} & "
            rf"{fmt(pre_we,0)} & {fmt(post_we,0)} & "
            rf"{fmt(pre_wc,0)} & {fmt(post_wc,0)} \\"
        )
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    # ------------------------------------------------------------------ #
    # 6. Brave – tracker blocking
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Brave Browser --- Tracker Blocking}\label{sec:brave}")

    b_avg = q(
        conn,
        """SELECT ROUND(AVG(block_rate_pct),1), MAX(block_rate_pct),
                  ROUND(AVG(total_requests),0), ROUND(AVG(blocked_count),1),
                  ROUND(AVG(lh_accessibility_score),1)
           FROM brave_scans WHERE is_error_page=0""",
    )[0]

    high_block = q(
        conn,
        "SELECT url, block_rate_pct, blocked_count FROM brave_scans "
        "WHERE is_error_page=0 ORDER BY block_rate_pct DESC LIMIT 3",
    )
    zero_block = q(
        conn,
        "SELECT COUNT(*) FROM brave_scans WHERE is_error_page=0 AND block_rate_pct=0",
    )[0][0]
    brave_total = q(conn, "SELECT COUNT(*) FROM brave_scans WHERE is_error_page=0")[0][0]

    emit(
        r"Brave's built-in shield blocked an average of "
        rf"\textbf{{{fmt(b_avg[0])}\,\%}} of network requests per page "
        rf"(mean {fmt(b_avg[3])} blocked out of {fmt(b_avg[2],0)} total requests). "
        rf"The highest block rates were recorded on "
        rf"\texttt{{{latex_escape(high_block[0][0])}}} ({fmt(high_block[0][1])}\,\%), "
        rf"\texttt{{{latex_escape(high_block[1][0])}}} ({fmt(high_block[1][1])}\,\%), "
        rf"and \texttt{{{latex_escape(high_block[2][0])}}} ({fmt(high_block[2][1])}\,\%). "
        rf"{zero_block} of {brave_total} reachable sites had no requests blocked at all."
    )
    emit()
    emit(
        rf"The average Brave Lighthouse accessibility score was \textbf{{{fmt(b_avg[4])}}}, "
        r"broadly in line with Chrome scores, indicating that Brave's blocking does not "
        r"materially impair measured accessibility."
    )
    emit()

    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Brave scan aggregate statistics}")
    emit(r"\begin{tabular}{lr}")
    emit(r"\toprule Metric & Value \\ \midrule")
    emit(rf"Average block rate & {fmt(b_avg[0])}\,\% \\")
    emit(rf"Maximum block rate & {fmt(b_avg[1])}\,\% \\")
    emit(rf"Avg.\ total requests/page & {fmt(b_avg[2],0)} \\")
    emit(rf"Avg.\ blocked requests/page & {fmt(b_avg[3])} \\")
    emit(rf"Sites with 0\,\% block rate & {zero_block} \\")
    emit(rf"Avg.\ Lighthouse score & {fmt(b_avg[4])} \\")
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    emit(
        r"Table~\ref{tab:brave} gives per-site figures. "
        r"Sites are ordered by descending block rate. "
        r"LH = Lighthouse accessibility score; Err = WAVE errors; Con = WAVE contrast errors."
    )
    emit()

    brave_rows = q(
        conn,
        """SELECT url, total_requests, blocked_count, block_rate_pct,
                  lh_accessibility_score, wave_error, wave_contrast
           FROM brave_scans WHERE is_error_page=0
           ORDER BY block_rate_pct DESC""",
    )
    emit(r"\begin{table}[ht]\centering\footnotesize")
    emit(r"\caption{Per-site Brave blocking and accessibility}\label{tab:brave}")
    emit(r"\begin{tabular}{>{\ttfamily}p{2.2cm} r r r r r r}")
    emit(r"\toprule \normalfont URL & Req & Blk & \% & LH & Err & Con \\ \midrule")
    for url, total, blocked, rate, lh, we, wc in brave_rows:
        emit(
            rf"  {latex_escape(url)} & "
            rf"{fmt(total,0)} & {fmt(blocked,0)} & {fmt(rate)}\,\% & "
            rf"{fmt(lh)} & {fmt(we,0)} & {fmt(wc,0)} \\"
        )
    emit(r"\bottomrule\end{tabular}")
    emit(r"\end{table}")

    # ------------------------------------------------------------------ #
    # 7. Control options summary (user-facing taxonomy)
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Cookie Notice Control Options and GDPR}")

    # --- Chrome counts by control type × emphasis ---
    ct_rows = q(
        conn,
        "SELECT cookie_control_type, cookie_emphasized_option, COUNT(*) "
        "FROM chrome_scans WHERE cookie_notice_detected=1 "
        "GROUP BY cookie_control_type, cookie_emphasized_option",
    )
    ct_map = {(ct, em): cnt for ct, em, cnt in ct_rows}

    no_notice_chrome = q(
        conn,
        "SELECT COUNT(*) FROM chrome_scans WHERE cookie_notice_detected=0 AND is_error_page=0",
    )[0][0]

    n_i_none   = ct_map.get(("accept_or_reject",           "equal"), 0)
    n_ii_none  = ct_map.get(("accept_or_settings",         "equal"), 0)
    n_iii_none = ct_map.get(("accept_reject_or_settings",  "equal"), 0) \
               + ct_map.get(("accept_reject_or_settings",  "none"),  0)
    n_iv       = ct_map.get(("informational_only",          "none"),  0)

    emit(
        r"Table~\ref{tab:options} classifies all reachable sites by the control options "
        r"offered to visitors in Chrome, using the taxonomy from the paper. "
        r"Cookie notices were not classified in Brave because the Brave scan did not "
        r"include a notice-detection step; Brave's block rates are analysed separately "
        r"in Section~\ref{sec:brave}. "
        r"The \textbf{GDPR violation} column indicates whether the notice design "
        r"satisfies the GDPR requirement for freely given, unambiguous consent: "
        r"notices that offer no explicit reject path are considered non-compliant."
    )
    emit()

    emit(r"\begin{table}[t]\centering\footnotesize")
    emit(r"\caption{Cookie notice control options (Chrome) and GDPR compliance.}\label{tab:options}")
    emit(r"\begin{tabular}{llrr} \toprule")
    emit(r"  \textbf{Control options} & \textbf{Emphasised option} & \textbf{Sites} & \textbf{GDPR violation} \\ \midrule")
    emit(rf"  (i) Agree or Reject  & None  & {n_i_none}  & No \\")
    emit(rf"  (ii) Agree or Settings & None & {n_ii_none} & Yes \\")
    emit(rf"  (iii) Agree, Reject  & None  & {n_iii_none} & No \\")
    emit(r"  \quad or Settings & & & \\[-6pt]")
    emit(rf"  (iv) Informational Only & --- & {n_iv} & Yes \\")
    emit(rf"  \multicolumn{{2}}{{l}}{{(v) No Notice}} & {no_notice_chrome} & Yes \\")
    emit(r"  \bottomrule\end{tabular}")
    emit(r"\end{table}")

    # ------------------------------------------------------------------ #
    # 8. Pre-accept vs post-accept vs Brave accessibility comparison
    # ------------------------------------------------------------------ #
    emit(r"\subsection{Accessibility: Pre, Post, and Brave Comparison}")

    matched = q(
        conn,
        """SELECT
             ROUND(AVG(c.pre_lh_score),1),    ROUND(AVG(c.post_lh_score),1),    ROUND(AVG(b.lh_accessibility_score),1),
             ROUND(AVG(c.pre_wave_error),1),   ROUND(AVG(c.post_wave_error),1),  ROUND(AVG(b.wave_error),1),
             ROUND(AVG(c.pre_wave_contrast),1),ROUND(AVG(c.post_wave_contrast),1),ROUND(AVG(b.wave_contrast),1),
             ROUND(AVG(c.pre_wave_alert),1),   ROUND(AVG(c.post_wave_alert),1),  ROUND(AVG(b.wave_alert),1),
             COUNT(*)
           FROM chrome_scans c
           JOIN brave_scans b ON c.url = b.url
           WHERE c.cookie_notice_detected=1 AND c.is_error_page=0 AND b.is_error_page=0
           AND c.pre_lh_score IS NOT NULL AND b.lh_accessibility_score IS NOT NULL""",
    )[0]

    pre_lh,  post_lh,  brave_lh  = matched[0],  matched[1],  matched[2]
    pre_we,  post_we,  brave_we  = matched[3],  matched[4],  matched[5]
    pre_wc,  post_wc,  brave_wc  = matched[6],  matched[7],  matched[8]
    pre_wa,  post_wa,  brave_wa  = matched[9],  matched[10], matched[11]
    n_matched = matched[12]

    def delta(a, b):
        if a is None or b is None:
            return "---"
        d = round(b - a, 1)
        return rf"\textbf{{{d:+.1f}}}" if d != 0 else "0.0"

    emit(
        rf"Table~\ref{{tab:a11y}} compares accessibility metrics across three states "
        rf"for the {n_matched} sites that had a cookie notice in Chrome and a successful "
        r"Brave scan: "
        r"\textbf{Chrome Pre} (cookie notice visible), "
        r"\textbf{Chrome Post} (after accepting the notice), and "
        r"\textbf{Brave} (ad-blocker enabled, no post-accept step). "
        r"$\Delta$\,Post shows the change after accepting the notice; "
        r"$\Delta$\,Brave shows the change relative to Chrome~Pre."
    )
    emit()
    emit(
        rf"Lighthouse scores were nearly identical across all three states "
        rf"({fmt(pre_lh)}, {fmt(post_lh)}, {fmt(brave_lh)}), "
        r"indicating that cookie notice overlays have negligible impact on measured "
        r"accessibility scores. "
        rf"WAVE alerts showed the largest reduction post-acceptance "
        rf"($\Delta = {fmt(post_wa - pre_wa if post_wa and pre_wa else None)}$), "
        r"likely because the notice overlay itself contributed alert-level issues "
        r"(e.g.\ redundant links or missing ARIA labels) that disappear once dismissed. "
        rf"Brave's contrast-error average ({fmt(brave_wc)}) was lower than Chrome~Pre "
        rf"({fmt(pre_wc)}), suggesting that some contrast issues originate in "
        r"ad/tracker content that Brave blocks."
    )
    emit()

    emit(r"\begin{table}[t]\centering\footnotesize")
    emit(
        rf"\caption{{Mean accessibility metrics across {n_matched} matched sites"
        r" (cookie-notice sites only)."
        r" LH\,=\,Lighthouse score (0--100); higher is better."
        r" WAVE metrics: lower is better.}\label{tab:a11y}"
    )
    emit(r"\begin{tabular}{lrrrrr} \toprule")
    emit(r"  \textbf{Metric} & \textbf{Chr.\ Pre} & \textbf{Chr.\ Post} & $\Delta$\,\textbf{Post}")
    emit(r"                  & \textbf{Brave}     & $\Delta$\,\textbf{Brave} \\ \midrule")
    emit(rf"  Lighthouse score    & {fmt(pre_lh)} & {fmt(post_lh)} & {delta(pre_lh,post_lh)} & {fmt(brave_lh)} & {delta(pre_lh,brave_lh)} \\")
    emit(rf"  WAVE errors         & {fmt(pre_we)} & {fmt(post_we)} & {delta(pre_we,post_we)} & {fmt(brave_we)} & {delta(pre_we,brave_we)} \\")
    emit(rf"  WAVE contrast errs  & {fmt(pre_wc)} & {fmt(post_wc)} & {delta(pre_wc,post_wc)} & {fmt(brave_wc)} & {delta(pre_wc,brave_wc)} \\")
    emit(rf"  WAVE alerts         & {fmt(pre_wa)} & {fmt(post_wa)} & {delta(pre_wa,post_wa)} & {fmt(brave_wa)} & {delta(pre_wa,brave_wa)} \\")
    emit(r"  \bottomrule\end{tabular}")
    emit(r"\end{table}")

    # ------------------------------------------------------------------ #
    # emit(r"\end{document}")
    return "\n".join(lines)


def main():
    conn = sqlite3.connect(DB_PATH)
    try:
        tex = build_report(conn)
    finally:
        conn.close()

    OUT_PATH.write_text(tex, encoding="utf-8")
    print(f"Written: {OUT_PATH}")


if __name__ == "__main__":
    main()
